### ISSUE TITLE
Need to have a more descriptive name for the Web.Style and Mobile.Style

### ISSUE THREAD

**Issue by LindsayThomas** [Esri/solutions-symbology-data#10]
the name says "web" in the style reference. It doesn't describe what the type of symbols the are 
![screen shot 2015-06-10 at 4 01 53 pm](https://cloud.githubusercontent.com/assets/2379312/8092762/27d7c13c-0f8a-11e5-9314-007d9a3236e6.png)

Maybe GovernmentWeb.Style

**Comment by HeatherEisan** [comment]
@LindsayThomas I could rename the style file to solutionweb? Because the style file also contains utility and emergency management symbols and not just government symbols. What do you think?

**Comment by LindsayThomas** [comment]
@HeatherEisan lets discuss post UC

**Comment by HeatherEisan** [comment]
Rename style files from desktop, web, mobile, to ArcGISSolutionsDesktop, ArcGISSolutionsWeb, and ArcGISSolutionsMobile.
