### ISSUE TITLE
ArcGIS Solution Map Symbols - July 2015

### ISSUE THREAD

**Issue by HeatherEisan** [Esri/solutions-symbology-data#13]
Point Symbols
- [x] Bridges
- [x] Road Block
- [x] Disaster Recovery Center
- [x] Emergency Clothing Distribution Center
- [x] First Aid station
- [x] Food Distribution Center
- [x] Incident Command Post 
- [x] Medivac Site
- [x] Pet Collection Area
- [x] Staging Area 
- [x] Water Distribution Center
- [x] Animal Health Emergency
- [x] Emergency Medical Services
- [x] Fire and Hazardous Materials
- [x] Incident Management
- [x] Law Enforcement and Security
- [x] Medical and Public Health
- [x] Search and Rescue
- [x] Emergency Assistance

Line Symbols
- [x] Road Closures
- [x] Road Detours

Polygon Symbols
- [x] Agriculture Animal Health Incident
- [x] Air Incident
- [x] Civil Disturbance Incident
- [x] Criminal Activity Incident
- [x] Fire Incident
- [x] Geologic Incident
- [x] Hazardous Material Incident
- [x] Hydro-Meteorological Incident
- [x] Infestation Incident
- [x] Marine Incident
- [x] Public Health Incident
- [x] Rail Incident
- [x] Vehicle Incident

**Comment by jrweakland** [comment]
@HeatherEisan - By chance have you checked out MIL-STD-2525D (Joint Military Symbology) for some of these icons? Please let me know if you are interested and I can show you the icons.

**Comment by HeatherEisan** [comment]
@jrweakland No I haven't, but when I do start to work on the symbols above I'll make sure to check them out. Thanks.

**Comment by WalterPotts** [comment]
Add Medical Response team and Rescue teams to the list. Also, change the source for Command Post, Staging and First Aid.  All of these items are available in the EmergencyFacility feature class in the Public  Safety Planning dataset.

**Comment by ScottOppmann** [comment]
@HeatherEisan - lets make sure we look at the GSTOP and NAPSG symbols for many of these features.

**Comment by HeatherEisan** [comment]
The symbols above have been merged into the repo. Closing issue.

**Comment by jrweakland** [comment]
@Dbarnes1
