### ISSUE TITLE
Add additional symbols for all of the Operational Status values for Shelters. 

### ISSUE THREAD

**Issue by jeffbaranyi** [Esri/solutions-symbology-data#27]
Add additional symbols for all of the Operational Status values for Shelters.  This includes Alert, Standby, and Unknown.

![sheltersymbolneeds](https://cloud.githubusercontent.com/assets/5030938/11939173/7e84f93c-a7dd-11e5-9a94-e29ab4bd72ce.png)

**Comment by HeatherEisan** [comment]
@jeffbaranyi shelter status (alert, standby, unknown) symbols have been added to the repo. They are located in both the ArcGISSolutionsWeb (ArcMap and ArcPro) style files as well as in the new ArcGISforEmergencyManagement (ArcMap and ArcPro).

**Comment by jeffbaranyi** [comment]
@HeatherEisan Sweet!  Thanks!
