### ISSUE TITLE
New Image Reference Page for Symbol Library

### ISSUE THREAD

**Issue by ScottOppmann** [Esri/solutions-symbology-data#32]
Create a new HTML page that can be used to reference symbols by URL in AGOL.  This HTML page will include a PNG image and the name of the symbol.  

Talk to @chris-fox about how we might implement.  We'd like this page to live in the repo.

**Comment by MikeMillerGIS** [comment]
You could use gh-pages branch to host it

Sent from my Verizon Wireless 4G LTE DROID
On Apr 20, 2016 3:30 PM, Scott Oppmann <notifications@github.com> wrote:

Create a new HTML page that can be used to reference symbols by URL in AGOL. This HTML page will include a PNG image and the name of the symbol.

Talk to @chris-fox<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_chris-2Dfox&d=CwMCaQ&c=n6-cguzQvX_tUIrZOS_4Og&r=hoBw6CQuytVR65zzd5i-Zw&m=Q7AU18mZa4KPWlADvIDEIwRsLTb42a8yhW-e-qZpI08&s=REyXKBgCK63_7G3Vmb8bfyXfpzdB7QtVKbK_GjjPq1c&e=> about how we might implement. We'd like this page to live in the repo.

**Comment by csmoore** [comment]
HTML or even Markdown would be a great way to document - I think you do have the ability to direct link to these images now - for instance in KML/popup (but getting the URL isn't overly friendly so a doc'd link page would definitely help) Ex:

![Sample Image Link](https://raw.githubusercontent.com/Esri/solutions-symbology-data/master/symbology/mobile/png/Asset-Misplaced.png)

https://raw.githubusercontent.com/Esri/solutions-symbology-data/master/symbology/mobile/png/Asset-Misplaced.png

We were incidentally going to do something similar for the military symbols - but then someone from the community wrote a pretty amazing Node Client app (gh-pages hosted) that eliminated the need: http://kjellmf.github.io/military-symbology-explorer

**Comment by MikeMillerGIS** [comment]
If people are going to be using the symbols for production apps, then I think we need to move the symbols to the solution site and not use the github hosting server.  Be nice to have a symbology html page on there and people could get the urls for an image they want to use and rely on it for mapping

**Comment by ScottOppmann** [comment]
@MikeMillerGIS - Good idea, we could have a nice set of pages on the solution site we could all link to.  @HeatherEisan  - could you think through this a bit more and come up with a prototype in the next week or so?

**Comment by NikkiGolding** [comment]
Where are we on the proto?
