### ISSUE TITLE
Wind.png not loading

### ISSUE THREAD

**Issue by karmstro77** [Esri/solutions-symbology-data#35]
I am unable to view the wind.png file. Looks like the link is broken.

![image](https://cloud.githubusercontent.com/assets/6819070/15256402/69cbac18-190f-11e6-905b-ce9b69423e97.png)

**Comment by HeatherEisan** [comment]
@karmstro77 Can you provide the page URL your trying to view the image from?

**Comment by karmstro77** [comment]
Seems to be working now, must have been a browser issue.

https://github.com/Esri/solutions-symbology-data/blob/4c913ec4476788a6ad0ff7402b0a1afbe3ced018/symbology/web/png/Wind.png

**Comment by HeatherEisan** [comment]
Good to hear.
