### ISSUE TITLE
New MUTCD symbol set and layer file

### ISSUE THREAD

**Issue by ScottOppmann** [Esri/solutions-symbology-data#38]
Create a new set of symbols for the MUTCD sign types.  Additional information found here:

http://mutcd.fhwa.dot.gov/shsm_interim/index.htm

Will want to prioritize which types we focus on first and what environments we are developing for. 

FYI @LindsayThomas @jlindemann @HeatherEisan

**Comment by tpcolson** [comment]
any status on this?

**Comment by TheMapSmith** [comment]
I work for a state transportation agency, and having access to a pre-built layer file with symbols for each MUTCD code would help us tremendously.
