### ISSUE TITLE
Add/Update with Pro Stylx Versions of symbol sets

### ISSUE THREAD

**Issue by csmoore** [Esri/solutions-symbology-data#6]
Just to continue to keep these under version control.  You can just add a stylx folder.

**Comment by csmoore** [comment]
I actually forgot that I made a vector-based version of these for 10.X/Pro: 

https://github.com/Esri/solutions-symbology-data/blob/master/data/solutions-symbology-combined  

If these meet your needs & can be used as the current version in the template - then this is done.

But if you have changes or used something else we'll need to update the repo to the latest version.

**Comment by conklinbd** [comment]
Closing since I think this is resolved.
